import { createClient } from "@/lib/supabase/server";
import { getWorkspaceContext } from "@/lib/workspace";
import { MetricCard } from "@/components/dashboard/metric-card";
import { OnboardingChecklist } from "@/components/dashboard/onboarding-checklist";
import { RecentJobs } from "@/components/dashboard/recent-jobs";
import { LeadQualitySummary } from "@/components/dashboard/lead-quality-summary";
export const dynamic = "force-dynamic";
async function getData() { try { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return { activeKeysCount: 0, requests: 0, cost: 0 }; const { workspaceId } = await getWorkspaceContext(user.id); const { data: keys } = await supabase.from("api_keys").select("id,status").eq("workspace_id", workspaceId); const activeKeysCount = (keys ?? []).filter((k: any) => k.status === "active").length; const { data: usage } = await supabase.from("usage_daily_rollups").select("request_count,cost_usd").eq("workspace_id", workspaceId).limit(31); return { activeKeysCount, requests: (usage ?? []).reduce((s: number, r: any) => s + Number(r.request_count ?? 0), 0), cost: (usage ?? []).reduce((s: number, r: any) => s + Number(r.cost_usd ?? 0), 0) }; } catch { return { activeKeysCount: 0, requests: 0, cost: 0 }; } }
export default async function DashboardPage() { const data = await getData(); return <main className="app-grid"><div><p className="eyebrow">Overview</p><h1 className="page-title">Lead generation control center</h1><p className="muted">Setup status, usage, recent jobs, and lead-quality workflow in one place.</p></div><section className="metrics-grid"><MetricCard label="Units remaining" value="Ready" hint="Billing page shows exact balance" /><MetricCard label="Leads found this month" value="—" hint="Populates from saved leads" /><MetricCard label="Average lead score" value="—" hint="V3 scores are persisted" /><MetricCard label="Requests last 30d" value={data.requests.toLocaleString()} hint={`$${data.cost.toFixed(2)} estimated cost`} /></section><section className="lead-finder-grid"><OnboardingChecklist activeKeysCount={data.activeKeysCount} /><LeadQualitySummary /></section><RecentJobs /></main>; }
