import { scoreLeadCandidates, type LeadCandidateV3 } from "@sales-ai/shared";
import type { LeadFinderEngine, LeadFinderRunInput, LeadFinderRunResult } from "./types.js";
export type SearchCompaniesFn = (input: LeadFinderRunInput) => Promise<LeadCandidateV3[]>;
export type ScrapeCompanyFn = (candidate: LeadCandidateV3, input: LeadFinderRunInput) => Promise<LeadCandidateV3>;
export type EnrichContactFn = (candidate: LeadCandidateV3, input: LeadFinderRunInput) => Promise<LeadCandidateV3>;
export type LeadFinderDeps = { searchCompanies: SearchCompaniesFn; scrapeCompany: ScrapeCompanyFn; enrichContact: EnrichContactFn; now: () => Date };
function domainName(url: string): string { try { return new URL(url).hostname.replace(/^www\./, ""); } catch { return url; } }
export function createMockLeadFinderDeps(): LeadFinderDeps { return { now: () => new Date(), async searchCompanies(input) { const domain = domainName(input.request.seller.website); const industries = input.request.target.industries.length ? input.request.target.industries : ["B2B SaaS"]; return Array.from({ length: Math.min(input.request.constraints.count + 3, 12) }, (_, index) => ({ id: `lead_${index+1}`, company: { name: `${industries[index % industries.length]} Prospect ${index+1}`, website: `https://prospect${index+1}.com`, industry: industries[index % industries.length], description: `${input.request.target.keywords.join(" ")} ${input.request.seller.description ?? domain}` }, contact: { name: `Buyer ${index+1}`, title: input.request.target.personas[0] ?? "Founder", email: `buyer${index+1}@prospect${index+1}.com`, emailConfidence: index % 3 === 0 ? "verified" : "pattern" }, signals: [{ type: "growth", label: "Growth signal", confidence: "medium" }, { type: "tech", label: "Relevant technology", confidence: "high" }], evidence: [{ title: "Company website", url: `https://prospect${index+1}.com`, quote: input.request.seller.valueProposition ?? "Relevant sales signal", capturedAt: input.llm.model ? new Date().toISOString() : new Date().toISOString() }], fitReasons: [`Matches ${domain} ICP inputs`] })); }, async scrapeCompany(candidate) { return candidate; }, async enrichContact(candidate) { return candidate; } }; }
export class ManagedV3LeadFinderEngine implements LeadFinderEngine { constructor(private deps: LeadFinderDeps = createMockLeadFinderDeps()) {} async run(input: LeadFinderRunInput): Promise<LeadFinderRunResult> { await input.onProgress?.({ stage: "target_strategy", progress: 20, message: "Building lead finder strategy." }); const discovered = await this.deps.searchCompanies(input); await input.onProgress?.({ stage: "company_discovery", progress: 40, message: `Discovered ${discovered.length} candidate companies.`, metadata: { discovered_count: discovered.length } }); const enriched: LeadCandidateV3[] = []; for (const candidate of discovered) { const scraped = await this.deps.scrapeCompany(candidate, input); enriched.push(await this.deps.enrichContact(scraped, input)); } await input.onProgress?.({ stage: "scoring", progress: 80, message: "Scoring leads against ICP." }); const leads = scoreLeadCandidates(enriched, input.request); await input.onProgress?.({ stage: "evidence_packaging", progress: 90, message: `Accepted ${leads.length} qualified leads.`, metadata: { accepted_count: leads.length } }); return { leads, stats: { discoveredCompanies: discovered.length, dedupedCompanies: discovered.length, reviewedCompanies: enriched.length, acceptedLeads: leads.length, crawlerRuns: 1, pagesCrawled: enriched.length, verificationRuns: enriched.length, estimatedCostUsd: Number((0.003 + enriched.length * 0.002).toFixed(6)) }, continuation: { needed: false } }; } }
