"use client";
import { use, useState } from "react";
import Link from "next/link";
import { redirect } from "next/navigation";
import { ToolForm } from "@/components/sales/tool-form";
import { ResultViewer } from "@/components/sales/result-viewer";
import { JobPoller } from "@/components/sales/job-poller";
import { ASYNC_ENDPOINTS, ENDPOINT_ALIASES, TOOL_INFO } from "@/lib/sales/endpoints";
type PageProps = { params: Promise<{ endpoint: string }> | { endpoint: string } };
export default function ToolPage({ params }: PageProps) { const resolvedParams = typeof (params as Promise<{endpoint:string}>).then === "function" ? use(params as Promise<{endpoint:string}>) : params as { endpoint: string }; const endpoint = ENDPOINT_ALIASES[resolvedParams.endpoint] || resolvedParams.endpoint; if (endpoint === "leads") redirect("/lead-finder"); const isAsync = ASYNC_ENDPOINTS.includes(endpoint as any); const tool = TOOL_INFO[endpoint]; const [result,setResult]=useState<any>(null); const [jobId,setJobId]=useState<string|null>(null); const [isLoading,setIsLoading]=useState(false); const [error,setError]=useState<string|null>(null); if(!tool) return <main><h1 className="page-title">Tool Not Found</h1><Link href="/sales" className="ui-button ui-button-secondary">Back</Link></main>; const handleSubmit=async(formData:Record<string,any>)=>{ setIsLoading(true); setError(null); setResult(null); setJobId(null); try{ const res=await fetch(`/api/sales/${endpoint}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(formData)}); const data=await res.json(); if(!res.ok) throw new Error(data.error?.message || "Request failed"); if(isAsync) setJobId(data.jobId); else setResult(data); }catch(err){ setError(err instanceof Error ? err.message : "An error occurred"); }finally{ setIsLoading(false); } }; return <main className="app-grid"><Link href="/sales" className="muted">← Back to AI Sales Tools</Link><div><h1 className="page-title">{tool.name}</h1><p className="muted">{tool.description}</p></div><div className="lead-finder-grid"><div className="ui-card"><h3>Run Tool</h3><ToolForm endpoint={endpoint} onSubmit={handleSubmit} isLoading={isLoading}/>{error&&<p className="ui-badge ui-badge-danger">{error}</p>}</div><div>{jobId && !result ? <JobPoller jobId={jobId} endpoint={endpoint} onComplete={setResult}/> : result ? <ResultViewer result={result}/> : <div className="ui-card"><p className="muted">Fill out the form and submit to see results.</p></div>}</div></div></main>; }
